[package]
name = "daisugi-consensus-transport-checks"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
types = { path = "../../lighthouse/consensus/types" }
execution_layer = { path = "../../lighthouse/beacon_node/execution_layer" }
ethereum_ssz = "0.10.0"
tree_hash = "0.12.0"
serde_json = "1"
sha2 = "0.10"
hex = "0.4"

[profile.dev]
debug = 0
incremental = false

[profile.test]
debug = 0
incremental = false
