/* ═══════════════════════════════════════════════════════════════════
   DashboardHeader — top bar with logo, identity, and action icons
   ───────────────────────────────────────────────────────────────────
   Shows:
     - Logo + wallet name ("nicetry")
     - Seed identifier label ("Seed Phrase 1 #1") — for now we only
       support one seed per vault, so this is static; wire it to real
       data when you add multi-seed support
     - Button to toggle the settings menu (popup ↔ sidebar switch is
       now inside the settings menu, dynamic based on current uiMode)

   The settings menu is rendered by the parent (Dashboard.jsx) so this
   component only fires the toggle callback.
   ═══════════════════════════════════════════════════════════════════ */

import { smartAddr, accounts, activeAccountIndex } from "@/ui/store.js";
import { useNetwork } from "@/ui/hooks/useNetwork.js";

function ChevronDownIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#a5a5a5" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="6 9 12 15 18 9" />
    </svg>
  );
}

function GearIcon() {
  return (
    <svg
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="#fafafa"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="3" />
      <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 1 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" />
    </svg>
  );
}

export function DashboardHeader({ onOpenSettings, onOpenAccounts, onOpenNetwork }) {
  // Display the signature profile and transaction format used by this build.
  const modeLabel = "SPHINCS-G · Native frames";

  // Active network for the switcher chip.
  const net = useNetwork();
  const networkName =
    net.network.value?.shortName || net.network.value?.name || "—";

  // Active account name for the switcher trigger.
  const activeIdx = activeAccountIndex.value;
  const active = (accounts.value || []).find((a) => a.index === activeIdx);
  const accountName = active?.name || `Account ${activeIdx + 1}`;

  // Per-account avatar generated by Dicebear thumbs. The seed is the
  // smart account address so each account gets a unique, deterministic
  // robot. Falls back to a stable seed when the address isn't loaded
  // yet (avoids a flash of a different avatar on first paint).
  const addr = smartAddr.value || "nicetry";
  const avatarUrl = `https://api.dicebear.com/9.x/thumbs/svg?seed=${encodeURIComponent(addr)}`;

  return (
    <div class="w-full flex items-start justify-between px-5 py-5 gap-3">
      <div class="flex items-center gap-3">
        <div
          class=" rounded-full shrink-0 overflow-hidden flex items-center justify-center"
          style={{ width: "42.667px", height: "42.667px" }}
        >
          <img
            src={avatarUrl}
            alt=""
            class="block w-full h-full"
            referrerPolicy="no-referrer"
          />
        </div>
        <div class="flex flex-col gap-1 items-start">
          <img
            src="/NiceTryText.svg"
            alt="nicetry"
            class="block select-none self-start"
            draggable={false}
            style={{
              width: "83.594px",
              height: "19.992px",
              aspectRatio: "83.59 / 19.99",
            }}
          />
          <button
            type="button"
            onClick={onOpenAccounts}
            title="Switch account"
            class="flex items-center gap-1 bg-transparent border-none cursor-pointer p-0 group"
          >
            <span class="font-['Poppins'] font-semibold text-[13px] leading-[1.2] text-[#fafafa] group-hover:text-[#6e88ec] transition-colors duration-150">
              {accountName}
            </span>
            <ChevronDownIcon />
          </button>
          <p class="font-['Poppins'] font-semibold text-[11px] leading-[1.2] text-[#767676] uppercase tracking-[0.44px]">
            {modeLabel}
          </p>
        </div>
      </div>

      <div class="flex items-center gap-2">
        <button
          type="button"
          onClick={onOpenNetwork}
          title="Switch network"
          class="h-10 px-3 bg-[#434343] border-b-2 border-[#3f56e3] flex items-center gap-1.5 cursor-pointer p-0 transition-colors duration-150 hover:bg-[rgba(63,86,227,0.2)]"
        >
          <span class="size-2 rounded-full bg-[#6e88ec] shrink-0" />
          <span class="font-['Poppins'] font-semibold text-[12px] leading-none text-[#fafafa] whitespace-nowrap">
            {networkName}
          </span>
          <ChevronDownIcon />
        </button>
        <button
          onClick={onOpenSettings}
          title="Settings"
          class="size-10 bg-[#434343] border-b-2 border-[#3f56e3] flex items-center justify-center cursor-pointer p-0 transition-colors duration-150 hover:bg-[rgba(63,86,227,0.2)]"
        >
          <GearIcon />
        </button>
      </div>
    </div>
  );
}
